# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

try:
    import question_pb2 as question__pb2
except ImportError:
    from web.proto_gen import question_pb2 as question__pb2

GRPC_GENERATED_VERSION = "1.83.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in question_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class QuestionServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListQuestions = channel.unary_unary(
            "/api.v1.QuestionService/ListQuestions",
            request_serializer=question__pb2.ListQuestionsRequest.SerializeToString,
            response_deserializer=question__pb2.ListQuestionsResponse.FromString,
            _registered_method=True,
        )
        self.GetQuestion = channel.unary_unary(
            "/api.v1.QuestionService/GetQuestion",
            request_serializer=question__pb2.GetQuestionRequest.SerializeToString,
            response_deserializer=question__pb2.Question.FromString,
            _registered_method=True,
        )
        self.CreateQuestion = channel.unary_unary(
            "/api.v1.QuestionService/CreateQuestion",
            request_serializer=question__pb2.CreateQuestionRequest.SerializeToString,
            response_deserializer=question__pb2.Question.FromString,
            _registered_method=True,
        )
        self.UpdateQuestion = channel.unary_unary(
            "/api.v1.QuestionService/UpdateQuestion",
            request_serializer=question__pb2.UpdateQuestionRequest.SerializeToString,
            response_deserializer=question__pb2.Question.FromString,
            _registered_method=True,
        )
        self.DeleteQuestion = channel.unary_unary(
            "/api.v1.QuestionService/DeleteQuestion",
            request_serializer=question__pb2.DeleteQuestionRequest.SerializeToString,
            response_deserializer=question__pb2.DeleteQuestionResponse.FromString,
            _registered_method=True,
        )
        self.ListTags = channel.unary_unary(
            "/api.v1.QuestionService/ListTags",
            request_serializer=question__pb2.ListTagsRequest.SerializeToString,
            response_deserializer=question__pb2.ListTagsResponse.FromString,
            _registered_method=True,
        )


class QuestionServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListQuestions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetQuestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateQuestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateQuestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteQuestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListTags(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_QuestionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ListQuestions": grpc.unary_unary_rpc_method_handler(
            servicer.ListQuestions,
            request_deserializer=question__pb2.ListQuestionsRequest.FromString,
            response_serializer=question__pb2.ListQuestionsResponse.SerializeToString,
        ),
        "GetQuestion": grpc.unary_unary_rpc_method_handler(
            servicer.GetQuestion,
            request_deserializer=question__pb2.GetQuestionRequest.FromString,
            response_serializer=question__pb2.Question.SerializeToString,
        ),
        "CreateQuestion": grpc.unary_unary_rpc_method_handler(
            servicer.CreateQuestion,
            request_deserializer=question__pb2.CreateQuestionRequest.FromString,
            response_serializer=question__pb2.Question.SerializeToString,
        ),
        "UpdateQuestion": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateQuestion,
            request_deserializer=question__pb2.UpdateQuestionRequest.FromString,
            response_serializer=question__pb2.Question.SerializeToString,
        ),
        "DeleteQuestion": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteQuestion,
            request_deserializer=question__pb2.DeleteQuestionRequest.FromString,
            response_serializer=question__pb2.DeleteQuestionResponse.SerializeToString,
        ),
        "ListTags": grpc.unary_unary_rpc_method_handler(
            servicer.ListTags,
            request_deserializer=question__pb2.ListTagsRequest.FromString,
            response_serializer=question__pb2.ListTagsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "api.v1.QuestionService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("api.v1.QuestionService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class QuestionService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListQuestions(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/api.v1.QuestionService/ListQuestions",
            question__pb2.ListQuestionsRequest.SerializeToString,
            question__pb2.ListQuestionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetQuestion(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/api.v1.QuestionService/GetQuestion",
            question__pb2.GetQuestionRequest.SerializeToString,
            question__pb2.Question.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CreateQuestion(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/api.v1.QuestionService/CreateQuestion",
            question__pb2.CreateQuestionRequest.SerializeToString,
            question__pb2.Question.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdateQuestion(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/api.v1.QuestionService/UpdateQuestion",
            question__pb2.UpdateQuestionRequest.SerializeToString,
            question__pb2.Question.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteQuestion(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/api.v1.QuestionService/DeleteQuestion",
            question__pb2.DeleteQuestionRequest.SerializeToString,
            question__pb2.DeleteQuestionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListTags(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/api.v1.QuestionService/ListTags",
            question__pb2.ListTagsRequest.SerializeToString,
            question__pb2.ListTagsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class SolutionServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSolution = channel.unary_unary(
            "/api.v1.SolutionService/GetSolution",
            request_serializer=question__pb2.GetSolutionRequest.SerializeToString,
            response_deserializer=question__pb2.Solution.FromString,
            _registered_method=True,
        )
        self.PutSolution = channel.unary_unary(
            "/api.v1.SolutionService/PutSolution",
            request_serializer=question__pb2.PutSolutionRequest.SerializeToString,
            response_deserializer=question__pb2.Solution.FromString,
            _registered_method=True,
        )
        self.ListMySolutions = channel.unary_unary(
            "/api.v1.SolutionService/ListMySolutions",
            request_serializer=question__pb2.ListMySolutionsRequest.SerializeToString,
            response_deserializer=question__pb2.ListMySolutionsResponse.FromString,
            _registered_method=True,
        )


class SolutionServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetSolution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PutSolution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListMySolutions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SolutionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetSolution": grpc.unary_unary_rpc_method_handler(
            servicer.GetSolution,
            request_deserializer=question__pb2.GetSolutionRequest.FromString,
            response_serializer=question__pb2.Solution.SerializeToString,
        ),
        "PutSolution": grpc.unary_unary_rpc_method_handler(
            servicer.PutSolution,
            request_deserializer=question__pb2.PutSolutionRequest.FromString,
            response_serializer=question__pb2.Solution.SerializeToString,
        ),
        "ListMySolutions": grpc.unary_unary_rpc_method_handler(
            servicer.ListMySolutions,
            request_deserializer=question__pb2.ListMySolutionsRequest.FromString,
            response_serializer=question__pb2.ListMySolutionsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "api.v1.SolutionService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("api.v1.SolutionService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class SolutionService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSolution(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/api.v1.SolutionService/GetSolution",
            question__pb2.GetSolutionRequest.SerializeToString,
            question__pb2.Solution.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def PutSolution(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/api.v1.SolutionService/PutSolution",
            question__pb2.PutSolutionRequest.SerializeToString,
            question__pb2.Solution.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListMySolutions(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/api.v1.SolutionService/ListMySolutions",
            question__pb2.ListMySolutionsRequest.SerializeToString,
            question__pb2.ListMySolutionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
